download:
	echo "Creating data directory"
	mkdir -p ./data
	echo "Downloading Paul Graham's essay"
	wget -O data/paul_graham_essay.txt https://raw.githubusercontent.com/run-llama/llama_index/main/docs/examples/data/paul_graham/paul_graham_essay.txt

clean:
	echo "Removing data directory"
	rm -rf ./data